### ISSUE TITLE
Review issues

### ISSUE THREAD

**Issue by lukasbystricky** [BR903/s-s-van-dine_the-greene-murder-case#1]
- [ ] modernize-spelling: negligé -> negligee (perhaps you'd reverted this, it looks strange to me too but apparently that's how MW spells it)
- [ ] find-mismatched-diacritics: I don't speak German, but are you sure that hätte/hatte and fälle/falle are correct as they are?
- [ ] there's a few unsemanticated italics hanging around, they seem to indicate that something is being read out loud. I think you can remove the italics in those cases. 
- [x] hausfrau appears in the unabridged MW, so italics can be removed
- [x] could the blockquote in chapter-23 be formatted as an ordered list? You can use the "start" property where appropriate, even for item 98
- [x] likewise in chapter-21, there's a blockquote that looks like it could be formatted as an unordered list
- [x] remove the div inside the blockquote for item 98 in chapter-23 and the blockquote in chapter-21

**Comment by BR903** [comment]
negligé -> negligee: This same word issue arose with "The Benson Murder Case". I convinced the reviewer that replacing the male-specific French word with the English version would suggest a completely different (and rather ridiculous) reading to modern readers, and so the original wording should be kept. I believe the same issue applies here.

hätte/hatte and fälle/falle: Since these German quotations are from a real book, I took the time to proofread the quotations against the actual book's text, so I am fairly confident they are correct as written. (Regarding your specific examples: "hatte" and "hätte" are two forms of the same irregular verb, while "Die Falle" and "Die Fälle" are two different nouns entirely.)

unsemanticated italics: I asked about these on the mailing list, and Emma's comment was: "I recommend keeping the italics, because the quoted text are translations. The italics differentiate the translations from other quoted text."

Hausfrau: If we change it so that it's English and not German, presumably we also need to decapitalize it as well, making this an Editorial change -- correct?

blockquote vs ordered list: I considered doing this, but I couldn't see how it would be advantageous to do so. The original book has the points formatted as paragraphs as it is. As the items in the list are explicitly referenced by number elsewhere in the book, it seemed better to keep them explicit in the text, so e.g. they can be searched for.

blockquote vs unordered list: Similarly, would turning the paragraphs into a list add anything (other than bullet points)?

divs inside blockquotes: Whoops! Thanks for catching those.

**Comment by lukasbystricky** [comment]
Ok, if there's precedent for keeping negligé then that's fine. I think it's better that way anyways. 

Regarding the unsemanticated italics, you're quite right that had already been addressed. Sorry about that. 

Hausfrau -> hausfrau can be editorial. 

The lists are more semantically correct. The numbers will still show up in the text so they can still be searched for if the reader wishes. One other advantage is that it keeps the indentation consistent. For the unordered list you can remove the bullet points using CSS.

**Comment by BR903** [comment]
Okay, I have changed the text to use lists in the manner you requested. However, I do wish to point out that the list numbers are in fact no longer searchable on the three ebook readers that I test with.

**Comment by lukasbystricky** [comment]
Hmm seems like you're right they can't be searched in Chrome either. Anyways, I think that's not that big an issue. It's semantically correct and it looks better if the indentation is handled properly. 

Are those numbers referenced anywhere other than endnote 30?

**Comment by BR903** [comment]
I'm not sure why this indentation is more "proper" -- in the original they are indented as normal paragraphs.... But no, they are only referenced in endnote 30.

**Comment by lukasbystricky** [comment]
I's how I would expect a list to be formatted in any case. That's in fact how I noticed initially that it wasn't formatted as an <ol>. But ok, that could be a personal preference. If you want to match the scans you could try adding something like:
`ol {
	margin: 0;
	padding: 0;
	list-style-position:inside;
}`

That keeps the semantics, which is the more important part. 

If some of them were referenced in more than one place then maybe it would have made sense to add hyperlinks to them, but endnote 30 would require a reader to go back to look at all of them. I don't think being able to search would help much there either.

**Comment by BR903** [comment]
I agree that adding hyperlinks would not be useful. (The tiny percentage of readers who are actually going to follow the suggestion of endnote 30 aren't going to be aided by having all of the numbers linked to approximately the same place.)

Thank you for the CSS (I was unfamiliar with "display: contents"). But if it is going to be formatted as an html list, it is probably better that it not seem to masquerade as normal text.

**Comment by lukasbystricky** [comment]
Ok, sounds good. I think this is ready for Alex then.
